"""Die Migrationskette ist der Weg, den JEDE Neuinstallation geht — und der
einzige Weg, den die Suite sonst nicht geht.

`conftest.pg_engine` baut sein Schema mit `Base.metadata.create_all`, nicht mit
Alembic. Ohne diese Datei prüft also **nichts**, ob `alembic upgrade head`
überhaupt durchläuft, ob das Ergebnis zu den Modellen passt und ob die beiden
Singleton-Zeilen entstehen, ohne die die App nicht startet. Eine kaputte
Migration wäre in einer vollständig grünen Suite unsichtbar und fiele erst der
ersten fremden Installation auf.

Zwei Dinge stehen hier bewusst NICHT:

- **Keine Aussage über die Anzahl der Migrationen.** Ab der Initialmigration ist
  jede weitere Änderung eine neue Datei; ein Test auf „genau eine" wäre beim
  ersten echten Schema-Update falsch und würde dann weggeklickt statt gelesen.
  Geprüft wird der eine *Kopf*, nicht die Länge der Kette.
- **Kein Vergleich gegen einen eingefrorenen Schema-Abzug.** Maßstab sind die
  Modelle (`alembic check`), damit der Test mit ihnen mitwandert. Ein
  eingefrorener Abzug wäre eine zweite Kopie des Schemas — die driftet.
"""
import os
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, text
from sqlalchemy.exc import OperationalError

from app.config import get_settings

MIGRATIONS_DB = "abgehakt_migrationstest"

# Absolut, nicht relativ: der Test darf nicht davon abhängen, aus welchem
# Verzeichnis pytest gestartet wurde.
_BACKEND = Path(__file__).resolve().parent.parent


def _alembic_config(url: str | None = None) -> Config:
    """Config OHNE `alembic.ini`.

    Absicht: `env.py` ruft `fileConfig()` nur, wenn `config_file_name` gesetzt
    ist. Das würde das Logging prozessweit umkonfigurieren (`disable_existing_
    loggers`) und andere Tests im selben Lauf beeinflussen. Die beiden Optionen,
    die die ini sonst liefert, setzen wir direkt.
    """
    cfg = Config()
    cfg.set_main_option("script_location", str(_BACKEND / "alembic"))
    if url:
        cfg.set_main_option("sqlalchemy.url", url)
    return cfg


@pytest.fixture(scope="module")
def migrationsdatenbank():
    """Leere Wegwerf-DB, auf der `alembic upgrade head` einmal echt läuft."""
    settings = get_settings()
    basis, _, _ = settings.database_url.rpartition("/")
    admin = create_engine(settings.database_url, isolation_level="AUTOCOMMIT", pool_pre_ping=True)
    try:
        with admin.connect() as conn:
            conn.execute(text(f"DROP DATABASE IF EXISTS {MIGRATIONS_DB} WITH (FORCE)"))
            conn.execute(text(f"CREATE DATABASE {MIGRATIONS_DB}"))
    except OperationalError:
        admin.dispose()
        pytest.skip("PostgreSQL nicht erreichbar – Migrationstest übersprungen")

    url = f"{basis}/{MIGRATIONS_DB}"
    cfg = _alembic_config(url)
    # `env.py` bevorzugt DATABASE_URL aus der Umgebung vor der Config — ohne das
    # hier liefe die Migration gegen die Produktionsdatenbank des Containers.
    vorher = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = url
    try:
        command.upgrade(cfg, "head")
        yield url, cfg
    finally:
        if vorher is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = vorher
        with admin.connect() as conn:
            conn.execute(text(f"DROP DATABASE IF EXISTS {MIGRATIONS_DB} WITH (FORCE)"))
        admin.dispose()


def test_kette_hat_genau_einen_kopf():
    """Zwei Köpfe = zwei Zweige, die nie zusammengeführt wurden.

    `alembic upgrade head` bricht dann mit „Multiple head revisions" ab — bei
    der fremden Installation, nicht bei uns.
    """
    koepfe = ScriptDirectory.from_config(_alembic_config()).get_heads()

    assert len(koepfe) == 1, f"Migrationskette hat {len(koepfe)} Köpfe: {koepfe}"


def test_upgrade_head_passt_zu_den_modellen(migrationsdatenbank):
    """Das Gate: nach der Migration darf `--autogenerate` nichts mehr zu tun haben.

    Läuft das auseinander, beschreibt das Archivschema etwas anderes als der
    Code — und der Unterschied fällt erst auf, wenn eine Abfrage auf eine Spalte
    trifft, die es in der migrierten Datenbank nicht gibt.
    """
    _, cfg = migrationsdatenbank

    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as abweichung:
        pytest.fail(f"Migration und Modelle laufen auseinander:\n{abweichung}")


def test_upgrade_head_legt_beide_singleton_zeilen_an(migrationsdatenbank):
    """`company` und `app_config` sind Singletons mit id=1.

    Die App legt sie nirgends an — sie erwartet sie. Fehlen sie, ist die
    frische Installation tot, bevor die erste Seite rendert.
    """
    url, _ = migrationsdatenbank
    engine = create_engine(url)
    try:
        with engine.connect() as conn:
            assert conn.execute(text("SELECT count(*) FROM company")).scalar() == 1
            assert conn.execute(text("SELECT count(*) FROM app_config")).scalar() == 1
    finally:
        engine.dispose()


def test_frische_firmenzeile_fuehrt_in_die_ersteinrichtung(migrationsdatenbank):
    """Leer ist der gewollte Wert, nicht ein vergessener.

    Die Firmenzeile trug ursprünglich die Daten einer fremden Firma als
    `server_default`. Wer die Software installiert, soll durch die
    Ersteinrichtung geführt werden und nicht Rechnungen im Namen eines
    Unbekannten stellen können.
    """
    url, _ = migrationsdatenbank
    engine = create_engine(url)
    try:
        with engine.connect() as conn:
            zeile = conn.execute(text(
                "SELECT name, address_line1, zip_code, city, setup_completed_at "
                "FROM company WHERE id = 1"
            )).one()
    finally:
        engine.dispose()

    assert zeile.name == ""
    assert zeile.address_line1 == ""
    assert zeile.zip_code == ""
    assert zeile.city == ""
    assert zeile.setup_completed_at is None
