"""Initialschema — die vollständige Datenbank einer Neuinstallation

Diese Datei ist **erzeugt** (`alembic revision --autogenerate`), nicht getippt.
Damit ist sie per Konstruktion deckungsgleich mit den Modellen, und
`alembic check` ist in diesem Repo ein echtes Gate (im Quell-Repo war es
dauerhaft rot und deshalb wertlos).

Zwei Dinge stehen nicht im ORM-Modell und sind von Hand ergänzt — übernommen
aus der abgelösten Migrationskette, nicht neu erfunden:

1. die GoBD-Trigger aus `app/db/immutability_triggers.py`. Dieselbe Quelle, aus
   der auch die Testdatenbank sie zieht — die DDL steht nirgends ein zweites Mal.
2. die beiden Singleton-Zeilen `company`/`app_config`; ohne sie startet die App nicht.

Nachweis, dass sie dasselbe Schema erzeugt wie die zwölf abgelösten Skripte:
`pg_dump --schema-only` beider Datenbanken, verglichen. Die verbliebenen
Unterschiede sind gewollt und einzeln begründet (Spaltenreihenfolge, NOT NULL
auf den Zeitstempeln, ein Unique-Index statt Constraint+Index).

Ab hier gilt der normale Ablauf: jede weitere Änderung ist eine **neue**
Migration. Diese Datei wird nie editiert.

Revision ID: 001
Revises:
Create Date: 2026-08-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.immutability_triggers import INSTALL_SQL, UNINSTALL_SQL


revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('datev_bcc_email', sa.String(length=255), nullable=True),
    sa.Column('invoice_cc_email', sa.String(length=255), nullable=True),
    sa.Column('update_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_latest_version', sa.String(length=32), nullable=True),
    sa.Column('update_severity', sa.String(length=16), nullable=True),
    sa.Column('update_notice', sa.String(length=500), nullable=True),
    sa.Column('update_url', sa.String(length=300), nullable=True),
    sa.Column('update_mitteilung_text', sa.String(length=500), nullable=True),
    sa.Column('update_mitteilung_url', sa.String(length=300), nullable=True),
    sa.Column('update_mitteilung_verworfen', sa.String(length=500), nullable=True),
    sa.Column('update_dismissed_version', sa.String(length=32), nullable=True),
    sa.Column('update_snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_table_record', 'audit_log', ['table_name', 'record_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='DE', nullable=False),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('vat_id', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bank_iban', sa.String(length=34), nullable=True),
    sa.Column('bank_bic', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), server_default='RE', nullable=False),
    sa.Column('invoice_year_in_number', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('invoice_counter', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payment_terms_default', sa.String(length=500), server_default='Zahlbar innerhalb von 14 Tagen nach Rechnungseingang ohne Abzug.', nullable=False),
    sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='DE', nullable=False),
    sa.Column('vat_id', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_number')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('net_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('zugferd_profile', sa.String(length=20), server_default='EN16931', nullable=False),
    sa.Column('tax_category', sa.String(length=5), server_default='S', nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('zugferd_xml', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('datev_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_until', sa.Date(), nullable=True),
    sa.Column('original_invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_issue_date'), 'invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_invoices_original_invoice_id'), 'invoices', ['original_invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='Stück', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='19', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_send_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('cc_email', sa.String(length=255), nullable=True),
    sa.Column('datev_bcc', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_send_log_invoice_id'), 'invoice_send_log', ['invoice_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('mustang_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # GoBD: Hard-Delete und TRUNCATE auf den Belegtabellen auf DB-Ebene sperren.
    # Zweite Verteidigungslinie hinter den Session-Guards — sie greift auch bei
    # manuellem psql und unabhängig von der Rolle.
    op.execute(INSTALL_SQL)

    # Die beiden Singletons. Die App legt sie nirgends an, sie erwartet sie.
    #
    # Die Firmenzeile entsteht LEER. Das ist der gewollte Wert, nicht ein
    # vergessener: `setup_completed_at IS NULL` führt die Nutzerin in die
    # Ersteinrichtung. Vorbelegte Firmendaten landeten sonst ungefragt in PDF,
    # ZUGFeRD-XML und Mailtext — im Namen einer fremden Firma.
    op.execute(
        "INSERT INTO company (id, name, address_line1, zip_code, city) "
        "VALUES (1, '', '', '', '') ON CONFLICT DO NOTHING"
    )
    op.execute("INSERT INTO app_config (id) VALUES (1) ON CONFLICT DO NOTHING")


def downgrade() -> None:
    op.execute(UNINSTALL_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_invoice_send_log_invoice_id'), table_name='invoice_send_log')
    op.drop_table('invoice_send_log')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_original_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issue_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('company')
    op.drop_index('ix_audit_log_table_record', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_config')
    # ### end Alembic commands ###
